
# GET http://localhost:3000
# Content-Type: application/json

# POST http://localhost:3000/v1/blogs/create-blog
# Content-Type: application/json

# {
#   "title": "How AI is Changing Web Development oka?",
#   "content": "Artificial Intelligence is revolutionizing web development by enabling smarter tools, better automation, and personalized user experiences. In this article, we explore how AI is integrated into modern frameworks, SaaS platforms, and development workflows.",
#   "image": "https://example.com/blog/ai-webdev.png",
#   "tags": ["AI", "Web Development", "SaaS", "JavaScript"]
# }

# GET http://localhost:3000/v1/blogs/get-blog/1
# Content-Type: application/json


# GET http://localhost:3000/v1/blogs/all-blogs?page=2&limit=5

# GET http://localhost:3000/v1/blogs/all-blogs?search=javascript

# GET http://localhost:3000/v1/blogs/all-blogs?page=2&limit=3

# GET http://localhost:3000/v1/blogs/all-blogs?sortBy=createdAt&sortOrder=desc

# GET http://localhost:3000/v1/blogs/all-blogs?sortBy=content&sortOrder=asc

# GET http://localhost:3000/v1/blogs/all-blogs?search=typescript&sortBy=title&sortOrder=asc&page=2&limit=3

# GET http://localhost:3000/v1/blogs/all-blogs?sortBy=tags&sortOrder=asc

# GET http://localhost:3000/v1/blogs/all-blogs?limit=5&page=1&search=changed

# GET http://localhost:3000/v1/blogs/all-blogs?sortBy=title&sortOrder=asc
# Content-Type: application/json



# GET http://localhost:3000/v1/blogs/all-blogs?limit=5&sortBy=title&sortOrder=asc&search=oka
# Content-Type: application/json

# GET http://localhost:3000/v1/blogs/all-blogs?search=JavaScript
# Content-Type: application/json

# GET http://localhost:3000/v1/blogs/all-blogs?page=2&limit=2
# Content-Type: application/json

# PATCH  http://localhost:3000/v1/blogs/update-blog/1
# Content-Type: application/json

# {
#     "tags": [
#       "IA",
#       "Web Development",
#       "JavaScript"
#     ],
#     "title": "How AI is Changing Web Development changed?"
# }

# DELETE  http://localhost:3000/v1/blogs/delete-blog/5
# Content-Type: application/json

# {
#   "title": "AI Blog Generator",
#   "description": "A full-stack app that generates blogs using AI and provides SEO-optimized drafts.",
#   "image": "https://example.com/project-image.png",
#   "slug": "ai-blog-generator",
#   "tags": ["AI", "Next.js", "Prisma", "PostgreSQL"],
#   "githubLink": "https://github.com/username/ai-blog-generator",
#   "liveLink": "https://ai-blog-generator.vercel.app/"
# }



# POST  http://localhost:3000/v1/projects/create-project
# Content-Type: application/json

# {
#   "title": "IA Blog Generator",
#   "description": "A full-stack app that generates blogs using AI and provides SEO-optimized drafts.",
#   "image": "https://example.com/project-image.png",
#   "slug": "ai-blog-generator",
#   "tags": ["AI", "Next.js", "Prisma", "PostgreSQL"],
#   "githubLink": "https://github.com/username/ai-blog-generatora",
#   "liveLink": "https://ai-blog-generator.vercel.appa/"
# }


# GET  http://localhost:3000/v1/projects/get-project/11sadas
# Content-Type: application/json
